### ISSUE TITLE
Not loading the tasks after Bugwarrior pull

### ISSUE THREAD

**Issue by excieve** [cinatic/taskwhisperer#14] opened 2016-03-19 22:42 UTC
I just pulled all the active relevant issues (60 of them) from JIRA using [Bugwarrior](https://bugwarrior.readthedocs.org/en/latest/index.html) extension to Timewarrior. After that "Reload Task Data" apparently does nothing, no errors in the system log either. After reloading Taskwhisperer extension no tasks are being shown at all (only the "...").

**Comment by cinatic** [comment] 2016-03-19 23:03
Could you provide me the output of:

`task rc.json.array=on status:Pending export`

you can also mail it to me to florijanh[at]gmail[dorts]com

**Comment by Aggharta** [comment] 2016-04-17 14:58
I encounter the same problem after installing it and adding tasks. I added the line `json.array=on` to the `.bashrc` file and restarted gnome. My output to your command is:
`[
{"id":1,"description":"Übung 1","due":"20160418T220000Z","entry":"20160417T125238Z","modified":"20160417T125238Z","project":"galgo","status":"pending","tags":["HA"],"uuid":"2282c533-8abb-4940-98a7-c462d5ca82b7","urgency":10.0067},
{"id":2,"description":"Pitch","due":"20160420T220000Z","entry":"20160417T130244Z","modified":"20160417T130244Z","project":"mmds","status":"pending","uuid":"983ec2a8-d63a-44fb-af26-0c7bf15eb641","urgency":8.29242}
]
Configuration override rc.json.array:on
`

**Comment by cinatic** [comment] 2016-04-21 06:56
hi @Aggharta 

thanks a lot for the input, i can't determine any deviation. Do you have the new Version installed maybe it was caused by an previour bug? (If it looks like on the picture then you have the new version =)

**Comment by cinatic** [comment] 2016-06-08 21:43
No further input or claims so i will close it =)

**Closed as completed by cinatic** 2016-06-08 21:43 UTC
Labels: bug
