### ISSUE TITLE
Starting/Stopping tasks produces lots of log messages and sometimes fails 

### ISSUE THREAD

**Issue by xrayn** [cinatic/taskwhisperer#92] opened 2021-05-11 09:15 UTC
Clicking on Task Start or Stop generates some weird entries in the journal logfile.

At the moment, tasks are started and stopped correctly. but earlier it happened that this did not work until I reloaded the extension. I could not reproduce it since.

My System is Arch
GNOME Shell 40.1
Package: gnome-shell 1:40.0+78+g954131c1c-1

```
May 11 10:55:12 lunar gnome-shell[1847]: Object St.BoxLayout (0x55ffdf12b990), has been already deallocated — impossible to access it. This might be caused by the object having been destroyed from C code using something such as destroy(), dispose(), or remove() vfuncs.
May 11 10:55:12 lunar gnome-shell[1847]: clutter_actor_destroy_all_children: assertion 'CLUTTER_IS_ACTOR (self)' failed
May 11 10:55:12 lunar gnome-shell[1847]: == Stack trace for context 0x55ffdcb0d120 ==
May 11 10:55:12 lunar gnome-shell[1847]: #0   55ffe8851bf8 i   /home/gg/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/components/flatList/flatList.js:45 (35fdc4767b50 @ 22)
May 11 10:55:12 lunar gnome-shell[1847]: #1   7ffc89ed3b50 b   /home/gg/.local/share/gnome-shell/extensions/taskwhisperer-extension@infinicode.de/components/screens/taskOverviewScreen/taskOverviewScreen.js:138 (35fdc4767240 @ 460)
May 11 10:55:12 lunar gnome-shell[1847]: #2   7ffc89ed3be0 b   self-hosted:693 (35fdc4773d80 @ 15)
...
```

**Comment by cinatic** [comment] 2021-05-11 10:09
thanks for the report it is indeed a severe stupid issue as it can cause refresh cycles and high cpu usage, caused by not explicitly unregister the previous refresh timer, will be fixed in the next version

https://github.com/cinatic/taskwhisperer/blob/master/taskwhisperer-extension%40infinicode.de/components/screens/taskOverviewScreen/taskOverviewScreen.js#L104

**Closed as completed** 2022-04-29 07:21 UTC
Labels: bug
